# name =
type = "webpack"

# account_id =
workers_dev = false
# route =
# zone_id =
compatibility_date = "2022-03-03"
webpack_config = "webpack.config.prod.cjs"

[env.test]
# These new values will override the top level configuration.
# name =
# account_id =
webpack_config = "webpack.config.cjs"
